### PR TITLE
Unit test expansion

### PR DESCRIPTION
**Pull request by Qalthos**
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/587

##### SUMMARY

Zuul says this is an increase to ~~58~~ 66% coverage, but does not run all the unit tests.
Local coverage results put this at ~~67~~ 68% coverage.
(Also both of these numbers are misleading, as they include coverage for files in the `tests/` dir that don't get executed)

##### ISSUE TYPE

- Test Pull Request

##### COMPONENT NAME

filter/ipaddr
modules/cli_config
module_utils/network/common/utils

### CODE REVIEW

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Pull request merged**
