### PR TITLE
Add testcase for netconf_config iosxr commit

### PR DESCRIPTION
**Pull request by ganeshrn**
Depends-On: https://github.com/ansible-collections/ansible.netcommon/pull/125
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/631
##### SUMMARY

Issue https://github.com/ansible-collections/cisco.iosxr/issues/74
Refer:
1) https://github.com/ansible-collections/cisco.iosxr/pull/76
2)  https://github.com/ansible/ansible/pull/71291
3) https://github.com/ansible/ansible/pull/71292

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

tests/integration/targets/netconf_config/tests/iosxr/basic.yaml
##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Comment by ganeshrn** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Pull request merged**
