### PR TITLE
Fix sanity tests

### PR DESCRIPTION
**Pull request by Qalthos**
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/557

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

net_*
netconf_config

### CODE REVIEW

**Comment by Qalthos** [comment]
recheck

**Comment by pabelanger** [comment]
Because we use ansible-test sanity from 2.9, we also need a backport of https://github.com/ansible/ansible/pull/70002 into stable-2.9. Then, eventually a 2.9 release.

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Pull request merged**
