### PR TITLE
This is to fix issue 71185

### PR DESCRIPTION
**Pull request by pszulczewski**
This was originally reported as an issue under: 
https://github.com/ansible/ansible/issues/71185

### CODE REVIEW

**Comment by Qalthos** [comment]
@pszulczewski could you please add a changelog? https://docs.ansible.com/ansible/latest/community/development_process.html#changelogs-how-to

**Comment by pszulczewski** [comment]
Changelog added. Thanks for reminder.

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Pull request merged**
