### PR TITLE
Add nxos netconf_config tests

### PR DESCRIPTION
**Pull request by mikewiebe**
##### SUMMARY
This PR adds back tests that used to be in `ansible/ansible`.

Original PR: https://github.com/ansible/ansible/pull/63593/files

This PR added the `get_filter` option and integration tests.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
netconf_config

Tested against version `9.3(3)`

### CODE REVIEW

**Review by ganeshrn — APPROVED** [review]
To run netconf test cases added in this PR for nxos instance in zuul will require to add netconf zuul job for nxos /cc @pabelanger @GomathiselviS

**Review by ganeshrn — COMMENTED** [review]
Please add changelog fragment.

**Comment by mikewiebe** [comment]
> Please add changelog fragment.

Hi @ganeshrn, I already had added a changelog fragment. `changelogs/fragments/netconf_nxos_tests.yaml`.  Is there something else that is needed?

**Comment by ganeshrn** [comment]
@mikewiebe Nothing from your side. It just that we need to enable netconf test run for nxos in our CI so that these are not repeated :)

**Comment by ganeshrn** [comment]
Since the nxos image in zuul is older and doesn't support netconf, merging the PR for now. Have raised a separate issue https://github.com/ansible-collections/ansible.netcommon/issues/200 to track enable CI to run for nxos netconf

**Comment by ganeshrn** [comment]
recheck

**Pull request merged**
