### PR TITLE
Update network_cli ssh_type default to use libssh

### PR DESCRIPTION
**Pull request by Qalthos**
##### SUMMARY

Depends-on: https://github.com/ansible/network-ee/pull/155
Depends-on: https://github.com/ansible/ansible-zuul-jobs/pull/1468

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

network_cli

### CODE REVIEW

**Review by cidrblock — APPROVED** [review]

**Comment by Qalthos** [comment]
recheck

**Comment by NilashishC** [comment]
@Qalthos something seems to going on with the tests. Default ssh_type is set to `auto`, but from the logs of the NX-OS job, it seems it is still picking up `paramiko`. It might be because it is getting overridden here: https://github.com/ansible/ansible-zuul-jobs/blob/master/zuul.d/cisco-nxos-jobs.yaml#L18? If that is the case, then `auto` would never be correctly tested.

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Pull request merged**
