### PR TITLE
Add more tests to ipaddr public query

### LINKED ISSUE #34: bug: ipaddr filter on empty list returns false instead of empty list
##### SUMMARY
Using the filter `ipaddr('public')` on an empty list returns `false`. It should return an empty list.

It correctly returns an empty list when used on a list with only private ips (e.g. `['192.168.1.0']|ipaddr('public')` returns `[]`)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ipaddr filter

##### ANSIBLE VERSION
```
ansible 2.9.7
  config file = /home/yannik/projects/arge-docs/ansible/ansible.cfg
  configured module search path = ['/home/yannik/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.7 (default, Mar 13 2020, 10:23:39) [GCC 9.2.1 20190827 (Red Hat 9.2.1-1)]

```

##### CONFIGURATION

```
ANSIBLE_NOCOWS(/home/yannik/projects/arge-docs/ansible/ansible.cfg) = True
ANSIBLE_PIPELINING(/home/yannik/projects/arge-docs/ansible/ansible.cfg) = True
DEFAULT_HOST_LIST(/home/yannik/projects/arge-docs/ansible/ansible.cfg) = ['/home/yannik/projects/arge-docs/ansible/hosts']
DEFAULT_MANAGED_STR(/home/yannik/projects/arge-docs/ansible/ansible.cfg) = This file is managed by ansible and will be overwritten! Do not change it manually!
DEFAULT_ROLES_PATH(/home/yannik/projects/arge-docs/ansible/ansible.cfg) = ['/etc/ansible/vendor_roles', '/home/yannik/projects/arge-docs/ansible/vendor_roles']
RETRY_FILES_ENABLED(/home/yannik/projects/arge-docs/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT
fedora 31 host, debian buster target

##### STEPS TO REPRODUCE

```yaml
- debug: msg="{{ []|ipaddr('public') }}"  
```

##### EXPECTED RESULTS
```
TASK [my-role : debug] ********************************************************************************************************
ok: [my-host] => {
    "msg": []
}
```

##### ACTUAL RESULTS

Output:
```
TASK [my-role : debug] ********************************************************************************************************
ok: [my-host] => {
    "msg": false
}
```

### PR DESCRIPTION
**Pull request by Qalthos**
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/611

##### SUMMARY

Fixes #34

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

filter/ipaddr

### CODE REVIEW

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by ganeshrn** [comment]
Seems like failed due to env issue
```
    "item": "vsrx3-18.4R1",
    "msg": "Timeout when waiting for 38.108.68.133:830"
```

**Comment by pabelanger** [comment]
recheck

**Pull request merged**
