### PR TITLE
Update ssh connection play_context alongside network_cli's

### LINKED ISSUE #133: rescue task for network_cli connection fails starting in Ansible 2.9.10 (still fails in Ansible 2.9.12)
As per [the original issue](https://github.com/ansible/ansible/issues/71405), rolling back the network_cli.py changes from https://github.com/ansible/ansible/pull/69642 fixed the issue.

##### SUMMARY

The below playbook works fine in Ansible 2.9.9 (and earlier), but started failing in Ansible 2.9.10 (and still fails in Ansible 2.9.12). In particular, the task in the block section is expected to fail and the rescue task is expected to work. As of Ansible 2.9.10, the rescue task continues to fail.

```
---
- name: Test block and rescue
  hosts: arista5
  gather_facts: False
  tasks:
    - block:
        - name: Attempt configuration using an invalid password
          vars:
            ansible_ssh_pass: "foobar"
          eos_config:
            lines:
              - "ip name-server {{ dns_server1 }}"
              - "ip name-server {{ dns_server2 }}"

      rescue:
        - name: Try configuration again in rescue-block
          vars:
            ansible_ssh_pass: my_password
          eos_config:
            lines:
              - "ip name-server {{ dns_server1 }}"
              - "ip name-server {{ dns_server2 }}"
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
network_cli connection inside of block-rescue

##### ANSIBLE VERSION

# Failing version:

```paste below
$ ansible --version
ansible 2.9.12
  config file = /home/ktbyers/.ansible.cfg
  configured module search path = ['/home/ktbyers/napalm-ansible/napalm_ansible/modules', '/home/ktbyers/ansible-extras/ntc-ansible/library']
  ansible python module location = /home/ktbyers/VENV/py3_venv/lib64/python3.7/site-packages/ansible
  executable location = /home/ktbyers/VENV/py3_venv/bin/ansible
  python version = 3.7.8 (default, Jul 24 2020, 20:26:49) [GCC 7.3.1 20180712 (Red Hat 7.3.1-9)]
```

##### CONFIGURATION

```paste below
ACTION_WARNINGS(/home/ktbyers/.ansible.cfg) = False
DEFAULT_ACTION_PLUGIN_PATH(/home/ktbyers/.ansible.cfg) = ['/home/ktbyers/napalm-ansible/napalm_ansible/plugi
DEFAULT_FILTER_PLUGIN_PATH(/home/ktbyers/.ansible.cfg) = ['/home/ktbyers/ansible-extras/ntc-ansible/filter_p
DEFAULT_HOST_LIST(/home/ktbyers/.ansible.cfg) = ['/home/ktbyers/ansible-hosts.ini']
DEFAULT_MODULE_PATH(/home/ktbyers/.ansible.cfg) = ['/home/ktbyers/napalm-ansible/napalm_ansible/modules', '/
DEPRECATION_WARNINGS(/home/ktbyers/.ansible.cfg) = False
HOST_KEY_CHECKING(/home/ktbyers/.ansible.cfg) = False
PERSISTENT_COMMAND_TIMEOUT(/home/ktbyers/.ansible.cfg) = 40
RETRY_FILES_ENABLED(/home/ktbyers/.ansible.cfg) = False
```

##### EXPECTED RESULTS

I expected the rescue task to work as per the behavior in Ansible 2.9.9 and before. 

##### ACTUAL RESULTS

Failing output (below with -vvvv and using Ansible 2.9.12)

```paste below
$ ansible-playbook exercise2.yml -vvvv
ansible-playbook 2.9.12
  config file = /home/ktbyers/.ansible.cfg
  configured module search path = ['/home/ktbyers/napalm-ansible/napalm_ansible/modules', '/home/ktbyers/ansible-extras/ntc-ansible/library']
  ansible python module location = /home/ktbyers/VENV/py3_venv/lib64/python3.7/site-packages/ansible
  executable location = /home/ktbyers/VENV/py3_venv/bin/ansible-playbook
  python version = 3.7.8 (default, Jul 24 2020, 20:26:49) [GCC 7.3.1 20180712 (Red Hat 7.3.1-9)]
Using /home/ktbyers/.ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /home/ktbyers/ansible-hosts.ini as it did not pass its verify_file() method
script declined parsing /home/ktbyers/ansible-hosts.ini as it did not pass its verify_file() method
auto declined parsing /home/ktbyers/ansible-hosts.ini as it did not pass its verify_file() method
yaml declined parsing /home/ktbyers/ansible-hosts.ini as it did not pass its verify_file() method
Set default localhost to localhost
Parsed /home/ktbyers/ansible-hosts.ini inventory source with ini plugin
Loading callback plugin default of type stdout, v2.0 from /home/ktbyers/VENV/py3_venv/lib64/python3.7/site-packages/ansible/plugins/callback/default.py

PLAYBOOK: exercise2.yml ************************************************************************************
Positional arguments: exercise2.yml
verbosity: 4
connection: smart
timeout: 10
become_method: sudo
tags: ('all',)
inventory: ('/home/ktbyers/ansible-hosts.ini',)
forks: 5
1 plays in exercise2.yml

PLAY [Test block and rescue] *******************************************************************************
META: ran handlers

TASK [Attempt configuration using an invalid password] *****************************************************
task path: /home/ktbyers/ansible_course/class7/exercises/exercise2/exercise2.yml:7
<arista5.lasthop.io> attempting to start connection
<arista5.lasthop.io> using connection plugin network_cli
<arista5.lasthop.io> local domain socket does not exist, starting it
<arista5.lasthop.io> control socket path is /home/ktbyers/.ansible/pc/173ec2aa62
<arista5.lasthop.io> local domain socket listeners started successfully
<arista5.lasthop.io> loaded cliconf plugin eos from path /home/ktbyers/VENV/py3_venv/lib/python3.7/site-packages/ansible/plugins/cliconf/eos.py for network_os eos
<arista5.lasthop.io> 
<arista5.lasthop.io> local domain socket path is /home/ktbyers/.ansible/pc/173ec2aa62
<arista5.lasthop.io> ESTABLISH LOCAL CONNECTION FOR USER: ktbyers
<arista5.lasthop.io> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/ktbyers/.ansible/tmp/ansible-local-31508i9l83shb `"&& mkdir "` echo /home/ktbyers/.ansible/tmp/ansible-local-31508i9l83shb/ansible-tmp-1598034716.4984322-31521-170479135808634 `" && echo ansible-tmp-1598034716.4984322-31521-170479135808634="` echo /home/ktbyers/.ansible/tmp/ansible-local-31508i9l83shb/ansible-tmp-1598034716.4984322-31521-170479135808634 `" ) && sleep 0'
Using module file /home/ktbyers/VENV/py3_venv/lib64/python3.7/site-packages/ansible/modules/network/eos/eos_config.py
<arista5.lasthop.io> PUT /home/ktbyers/.ansible/tmp/ansible-local-31508i9l83shb/tmpwajb7rvz TO /home/ktbyers/.ansible/tmp/ansible-local-31508i9l83shb/ansible-tmp-1598034716.4984322-31521-170479135808634/AnsiballZ_eos_config.py
<arista5.lasthop.io> EXEC /bin/sh -c 'chmod u+x /home/ktbyers/.ansible/tmp/ansible-local-31508i9l83shb/ansible-tmp-1598034716.4984322-31521-170479135808634/ /home/ktbyers/.ansible/tmp/ansible-local-31508i9l83shb/ansible-tmp-1598034716.4984322-31521-170479135808634/AnsiballZ_eos_config.py && sleep 0'
<arista5.lasthop.io> EXEC /bin/sh -c '/home/ktbyers/VENV/ansible/bin/python /home/ktbyers/.ansible/tmp/ansible-local-31508i9l83shb/ansible-tmp-1598034716.4984322-31521-170479135808634/AnsiballZ_eos_config.py && sleep 0'
<arista5.lasthop.io> EXEC /bin/sh -c 'rm -f -r /home/ktbyers/.ansible/tmp/ansible-local-31508i9l83shb/ansible-tmp-1598034716.4984322-31521-170479135808634/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/ktbyers/.ansible/tmp/ansible-local-31508i9l83shb/ansible-tmp-1598034716.4984322-31521-170479135808634/AnsiballZ_eos_config.py", line 102, in <module>
    _ansiballz_main()
  File "/home/ktbyers/.ansible/tmp/ansible-local-31508i9l83shb/ansible-tmp-1598034716.4984322-31521-170479135808634/AnsiballZ_eos_config.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/ktbyers/.ansible/tmp/ansible-local-31508i9l83shb/ansible-tmp-1598034716.4984322-31521-170479135808634/AnsiballZ_eos_config.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.network.eos.eos_config', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.7/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_eos_config_payload_rtle3fxe/ansible_eos_config_payload.zip/ansible/modules/network/eos/eos_config.py", line 518, in <module>
  File "/tmp/ansible_eos_config_payload_rtle3fxe/ansible_eos_config_payload.zip/ansible/modules/network/eos/eos_config.py", line 397, in main
  File "/tmp/ansible_eos_config_payload_rtle3fxe/ansible_eos_config_payload.zip/ansible/module_utils/network/eos/eos.py", line 107, in get_connection
  File "/tmp/ansible_eos_config_payload_rtle3fxe/ansible_eos_config_payload.zip/ansible/module_utils/connection.py", line 185, in __rpc__
ansible.module_utils.connection.ConnectionError: Failed to authenticate: Bad authentication type; allowed types: ['publickey', 'keyboard-interactive']
fatal: [arista5]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/ktbyers/.ansible/tmp/ansible-local-31508i9l83shb/ansible-tmp-1598034716.4984322-31521-170479135808634/AnsiballZ_eos_config.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/ktbyers/.ansible/tmp/ansible-local-31508i9l83shb/ansible-tmp-1598034716.4984322-31521-170479135808634/AnsiballZ_eos_config.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/ktbyers/.ansible/tmp/ansible-local-31508i9l83shb/ansible-tmp-1598034716.4984322-31521-170479135808634/AnsiballZ_eos_config.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.network.eos.eos_config', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.7/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.7/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.7/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_eos_config_payload_rtle3fxe/ansible_eos_config_payload.zip/ansible/modules/network/eos/eos_config.py\", line 518, in <module>\n  File \"/tmp/ansible_eos_config_payload_rtle3fxe/ansible_eos_config_payload.zip/ansible/modules/network/eos/eos_config.py\", line 397, in main\n  File \"/tmp/ansible_eos_config_payload_rtle3fxe/ansible_eos_config_payload.zip/ansible/module_utils/network/eos/eos.py\", line 107, in get_connection\n  File \"/tmp/ansible_eos_config_payload_rtle3fxe/ansible_eos_config_payload.zip/ansible/module_utils/connection.py\", line 185, in __rpc__\nansible.module_utils.connection.ConnectionError: Failed to authenticate: Bad authentication type; allowed types: ['publickey', 'keyboard-interactive']\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

TASK [Try configuration again in rescue-block] *************************************************************
task path: /home/ktbyers/ansible_course/class7/exercises/exercise2/exercise2.yml:16
<arista5.lasthop.io> attempting to start connection
<arista5.lasthop.io> using connection plugin network_cli
<arista5.lasthop.io> found existing local domain socket, using it!
<arista5.lasthop.io> network_cli_retry: attempt: 1, caught exception(Failed to authenticate: Bad authentication type; allowed types: ['publickey', 'keyboard-interactive']), pausing for 2 seconds
<arista5.lasthop.io> network_cli_retry: attempt: 2, caught exception(Failed to authenticate: Bad authentication type; allowed types: ['publickey', 'keyboard-interactive']), pausing for 4 seconds
<arista5.lasthop.io> network_cli_retry: attempt: 3, caught exception(Failed to authenticate: Bad authentication type; allowed types: ['publickey', 'keyboard-interactive']), pausing for 8 seconds
<arista5.lasthop.io> updating play_context for connection
<arista5.lasthop.io> 
<arista5.lasthop.io> local domain socket path is /home/ktbyers/.ansible/pc/173ec2aa62
<arista5.lasthop.io> ESTABLISH LOCAL CONNECTION FOR USER: ktbyers
<arista5.lasthop.io> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/ktbyers/.ansible/tmp/ansible-local-31508i9l83shb `"&& mkdir "` echo /home/ktbyers/.ansible/tmp/ansible-local-31508i9l83shb/ansible-tmp-1598034735.59588-31615-28790253704584 `" && echo ansible-tmp-1598034735.59588-31615-28790253704584="` echo /home/ktbyers/.ansible/tmp/ansible-local-31508i9l83shb/ansible-tmp-1598034735.59588-31615-28790253704584 `" ) && sleep 0'
Using module file /home/ktbyers/VENV/py3_venv/lib64/python3.7/site-packages/ansible/modules/network/eos/eos_config.py
<arista5.lasthop.io> PUT /home/ktbyers/.ansible/tmp/ansible-local-31508i9l83shb/tmpnss8077h TO /home/ktbyers/.ansible/tmp/ansible-local-31508i9l83shb/ansible-tmp-1598034735.59588-31615-28790253704584/AnsiballZ_eos_config.py
<arista5.lasthop.io> EXEC /bin/sh -c 'chmod u+x /home/ktbyers/.ansible/tmp/ansible-local-31508i9l83shb/ansible-tmp-1598034735.59588-31615-28790253704584/ /home/ktbyers/.ansible/tmp/ansible-local-31508i9l83shb/ansible-tmp-1598034735.59588-31615-28790253704584/AnsiballZ_eos_config.py && sleep 0'
<arista5.lasthop.io> EXEC /bin/sh -c '/home/ktbyers/VENV/ansible/bin/python /home/ktbyers/.ansible/tmp/ansible-local-31508i9l83shb/ansible-tmp-1598034735.59588-31615-28790253704584/AnsiballZ_eos_config.py && sleep 0'
<arista5.lasthop.io> EXEC /bin/sh -c 'rm -f -r /home/ktbyers/.ansible/tmp/ansible-local-31508i9l83shb/ansible-tmp-1598034735.59588-31615-28790253704584/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/ktbyers/.ansible/tmp/ansible-local-31508i9l83shb/ansible-tmp-1598034735.59588-31615-28790253704584/AnsiballZ_eos_config.py", line 102, in <module>
    _ansiballz_main()
  File "/home/ktbyers/.ansible/tmp/ansible-local-31508i9l83shb/ansible-tmp-1598034735.59588-31615-28790253704584/AnsiballZ_eos_config.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/ktbyers/.ansible/tmp/ansible-local-31508i9l83shb/ansible-tmp-1598034735.59588-31615-28790253704584/AnsiballZ_eos_config.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.network.eos.eos_config', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.7/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_eos_config_payload_88yr221o/ansible_eos_config_payload.zip/ansible/modules/network/eos/eos_config.py", line 518, in <module>
  File "/tmp/ansible_eos_config_payload_88yr221o/ansible_eos_config_payload.zip/ansible/modules/network/eos/eos_config.py", line 397, in main
  File "/tmp/ansible_eos_config_payload_88yr221o/ansible_eos_config_payload.zip/ansible/module_utils/network/eos/eos.py", line 107, in get_connection
  File "/tmp/ansible_eos_config_payload_88yr221o/ansible_eos_config_payload.zip/ansible/module_utils/connection.py", line 185, in __rpc__
ansible.module_utils.connection.ConnectionError: Failed to authenticate: Bad authentication type; allowed types: ['publickey', 'keyboard-interactive']
fatal: [arista5]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/ktbyers/.ansible/tmp/ansible-local-31508i9l83shb/ansible-tmp-1598034735.59588-31615-28790253704584/AnsiballZ_eos_config.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/ktbyers/.ansible/tmp/ansible-local-31508i9l83shb/ansible-tmp-1598034735.59588-31615-28790253704584/AnsiballZ_eos_config.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/ktbyers/.ansible/tmp/ansible-local-31508i9l83shb/ansible-tmp-1598034735.59588-31615-28790253704584/AnsiballZ_eos_config.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.network.eos.eos_config', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.7/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.7/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.7/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_eos_config_payload_88yr221o/ansible_eos_config_payload.zip/ansible/modules/network/eos/eos_config.py\", line 518, in <module>\n  File \"/tmp/ansible_eos_config_payload_88yr221o/ansible_eos_config_payload.zip/ansible/modules/network/eos/eos_config.py\", line 397, in main\n  File \"/tmp/ansible_eos_config_payload_88yr221o/ansible_eos_config_payload.zip/ansible/module_utils/network/eos/eos.py\", line 107, in get_connection\n  File \"/tmp/ansible_eos_config_payload_88yr221o/ansible_eos_config_payload.zip/ansible/module_utils/connection.py\", line 185, in __rpc__\nansible.module_utils.connection.ConnectionError: Failed to authenticate: Bad authentication type; allowed types: ['publickey', 'keyboard-interactive']\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

PLAY RECAP *************************************************************************************************
arista5                    : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=1    ignored=0 
```

### PR DESCRIPTION
**Pull request by Qalthos**
##### SUMMARY

Fixes #133

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

network_cli

### CODE REVIEW

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Comment by ktbyers** [comment]
Any update on this? Shouldn't it also be back-ported to Ansible 2.9.X (since the original issue broke block/rescue when using network_cli)?

**Comment by ktbyers** [comment]
I tested this against the original failing situation that I reported and it fixed the underlying issue.

I was using:

```
$ pip list | grep ansible
ansible                      2.10.0
ansible-base                 2.10.2
```

And modified `network_cli.py` with the same change as detailed in this PR and my test case worked properly.

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
> Any update on this?

This got tabled in order to get netcommon 1.3.0 out on time. The "recheck" comments are queueing Zuul to rerun pre-merge checks that have to pass. There has been some slight instability there recently that led to the aforementioned shelving of this issue. That said, the patch is done, and you verified that it works, so it should be merged soon.

> Shouldn't it also be back-ported to Ansible 2.9.X (since the original issue broke block/rescue when using network_cli in a fairly meaningful way)?

As Ansible 2.10 is out now, we are following our established policy of only backporting security fixes to `ver-1` (2.9 in this case). This PR will be available when updating the collection through Galaxy or when a new version of 2.10 picks up a newer version of this collection.

I hope that gives you better insight into when you can expect to see this fixed without having to modify files yourself.

**Comment by ktbyers** [comment]
@Qalthos Ansible broke this going from 2.9.9 to 2.9.10 and I don't think the original change was a security fix--so shouldn't the original change be reverted back?

Obviously, 2.10 is a big change release so being stuck on 2.9.9 for a long time is pretty undesirable. Also I reported the underlying issue well before 2.10 was released (including that rolling back the PR that broke it...fixed the underlying issue).

**Comment by Qalthos** [comment]
You are correct. I think I had this confused with another issue... this one is probably still valid to backport to 2.9, and I'll open that PR as soon as this one gets merged.

**Comment by Qalthos** [comment]
recheck

**Pull request merged**
