### PR TITLE
Drop plugins/cache/base

### LINKED ISSUE #273: antsibull-changelog failing from undocumented base "cache plugin"
##### SUMMARY

When trying to generate the changelog for 2.0.2, I got the following:

```
% antsibull-changelog release --version 2.0.1
ERROR! cache ansible.netcommon.base missing documentation (or could not parse documentation): ansible.netcommon.base did not contain a DOCUMENTATION attribute
```

We can get away with this for action plugins, because they don't expect to have documentation, but it looks like we need to do something about it for cache. I'm assuming we can't use `__init__.py` because that's masked by the version in ansible/ansible, but I'm not sure what we can do for this.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

plugins/cache/base

### PR DESCRIPTION
**Pull request by Qalthos**
##### SUMMARY

Fixes #273 

##### ISSUE TYPE

- Bugfix Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by NilashishC — APPROVED** [review]

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Pull request merged**
