### PR TITLE
Apply comment tokens to NetworkConfig objects

### PR DESCRIPTION
**Pull request by Qalthos**
##### SUMMARY

This is step one of getting comment tokens overridden

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

module_utils/network/common/config

### CODE REVIEW

**Comment by rohitthakur2590** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Pull request merged**
