### PR TITLE
Ipaddr - Add valid network for link-local

### PR DESCRIPTION
**Pull request by ashwini-mhatre**
##### SUMMARY

Fixes: https://github.com/ansible-collections/ansible.netcommon/issues/343
Depends-on: https://github.com/ansible-collections/ansible.netcommon/pull/357

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

ipaddr
##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by Qalthos — APPROVED** [review]

**Comment by ashwini-mhatre** [comment]
recheck

**Comment by ashwini-mhatre** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Pull request closed without merging**
