### PR TITLE
Fix config diff logic in case of multiple parent lines

### PR DESCRIPTION
**Pull request by ganeshrn**
##### SUMMARY

Fixes https://github.com/ansible-collections/ansible.netcommon/issues/189

* If the parent config lines appear at multiple places in the
  configuration update list add it in the final diff along
  with child elements.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

module_utils/network/common/config.py

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by ipspace** [comment]
Going through the code I see what a huge can of worms this is ;) ... and it looks like you're doing exactly what needs to be done.

Reran my tests with your config_diff_fix branch of ansible.netcommon collection and it all works as expected. Thank you for fixing this so fast!

**Review by praveenramoorthy — APPROVED** [review]

**Comment by ganeshrn** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Comment by ganeshrn** [comment]
recheck

**Comment by ganeshrn** [comment]
recheck

**Comment by ganeshrn** [comment]
Seems like there is some issue related to infra. All the failed testcase are due to `Exception: command timeout triggered, timeout value is 100 secs.`

**Comment by ganeshrn** [comment]
recheck

**Comment by trishnaguha** [comment]
@GomathiselviS @pabelanger Can you please investigate the NODE FAILURE? It will block the release otherwise.

**Comment by GomathiselviS** [comment]
recheck

**Comment by ganeshrn** [comment]
vyos job `ansible-test-network-integration-vyos-network_cli-libssh-python36 — build history` failed with command timeout error

**Comment by ganeshrn** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Pull request merged**
