### PR TITLE
Support removal of non-config lines from running config while taking backup

### PR DESCRIPTION
**Pull request by NilashishC**
##### SUMMARY
Depends-on: https://github.com/ansible-collections/ansible.netcommon/pull/271
Depends-on: https://github.com/ansible/ansible-zuul-jobs/pull/1139

- This patch allows the platform specific config modules to remove non-config lines from backup files.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
action/network.py

### CODE REVIEW

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Review by Qalthos — APPROVED** [review]

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Pull request merged**
