### PR TITLE
Added test requirement to enable Unit tests in CI

### PR DESCRIPTION
**Pull request by GomathiselviS**
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/439

### CODE REVIEW

**Comment by pabelanger** [comment]
you'll need to add a zuul.yaml file for now, to include the new project-template, to confirm this works as expected

**Comment by trishnaguha** [comment]
@GomathiselviS @pabelanger Can we get this merged?

**Comment by pabelanger** [comment]
This looks to have pyc files (compiled code), lets remove them and zuul.yaml now

**Comment by pabelanger** [comment]
@trishnaguha no, see my reply above

**Pull request closed without merging**
