### PR TITLE
Add new base classes for Resource Modules

### PR DESCRIPTION
**Pull request by NilashishC**
Depends-On: https://github.com/ansible-collections/openvswitch.openvswitch/pull/12/

Signed-off-by: NilashishC <nilashishchakraborty8@gmail.com>

##### SUMMARY
- This PR adds new base classes that Resource Modules would use in the new approach.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
network_template.py
resource_module.py

### CODE REVIEW

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
Blocked by https://github.com/ansible/ansible/issues/69036

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by pabelanger** [comment]
I've proposed https://github.com/ansible/ansible-zuul-jobs/pull/440 to help deal with download failures for collections.

**Pull request merged**
