### PR TITLE
Remove cli_parse plugins and add redirection

### PR DESCRIPTION
**Pull request by Qalthos**
##### SUMMARY

Depends-on: https://github.com/ansible/zuul-config/pull/362
Depends-on: https://github.com/ansible/project-config/pull/1067

Remove plugins moved to ansible.utils

##### ISSUE TYPE

- Module Removal Pull Request

##### COMPONENT NAME

cli_parse

### CODE REVIEW

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
Can you add a `Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1415`?

**Comment by Qalthos** [comment]
recheck

**Comment by goneri** [comment]
We can disable vyos for now or add a `Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1392`. vyos is still broken because of an image problem.

**Comment by goneri** [comment]
Oh, the two PRs seem to conflict :-(.

**Comment by Qalthos** [comment]
It looks like https://github.com/ansible/ansible-zuul-jobs/pull/1392 already has a merge conflict right now?

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Pull request closed without merging**
