### PR TITLE
DO NOT MERGE - breaking change to ensure CI works fine

### PR DESCRIPTION
**Pull request by sshnaidm**
##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

DO NOT MERGE

##### ADDITIONAL INFORMATION

```paste below

```
DO NOT MERGE

### CODE REVIEW

**Comment by pabelanger** [comment]
@sshnaidm where is the pipeline config for rdo zuul again? We do not want the bot leaving comments here.  And instead using the check_run api

**Comment by pabelanger** [comment]
For example, you can look at our check pipeline for github app: https://github.com/ansible/project-config/blob/master/zuul.d/pipelines.yaml#L2

note we no longer have comments in the pipeline, those can be removed.

**Comment by TristanCacqueray** [comment]
The pipeline is defined in https://review.rdoproject.org/cgit/config/tree/zuul.d/github.yaml

**Comment by TristanCacqueray** [comment]
@sshnaidm could you re-open to see if the new pipeline fixed the authentication issue?

**Comment by TristanCacqueray** [comment]
@pabelanger Then should we remove the PR write permission?

**Comment by pabelanger** [comment]
@TristanCacqueray Yah, we likely can drop that now, as we'd never expect the bot to comment directly on the issue now.

**Comment by pabelanger** [comment]
rdoproject.org/github-check-ro Cancelled after 14s — Summary

rdoproject.org/github-check — github-check status: failure

Getting there, at least check_run API is now being used. But job looks to be in the incorrect pipeline?

**Comment by pabelanger** [comment]
okay, jobs in progress now. Lets see what happens

**Comment by TristanCacqueray** [comment]
On the executor, in the log there is:

```
2021-07-13 20:30:42,387 ERROR zuul.AnsibleJob: [e: 0d56c330-e418-11eb-8c15-706545fc1a7f] [build: d608e4fbdad6448aa0ccdc10bc146e74] Exception while executing job
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/zuul/executor/server.py", line 1026, in execute
    self._execute()
  File "/usr/lib/python3.6/site-packages/zuul/executor/server.py", line 1144, in _execute
    repo_state[task.connection_name][task.project_name]
KeyError: 'github.com'
```

**Comment by pabelanger** [comment]
@TristanCacqueray looks like something is still configured to use the 'github.com' trigger and not github-ro

**Comment by TristanCacqueray** [comment]
@pabelanger but this log is from the github-check-ro pipeline. Are you sure zuul can work with multiple applications? Looking at ansible 3pci pipeline, it seems like it never got used: https://dashboard.zuul.ansible.com/t/ansible/builds?pipeline=3pci-check

**Comment by pabelanger** [comment]
yes, multiple github apps should be fine. It is just a new github connection, long with proper pipeline config.

**Comment by pabelanger** [comment]
I can look more in the morning on zuul side, I suspect there is something configured to still use github.com connection, while it should be setup to use the readonly one.

**Comment by TristanCacqueray** [comment]
The collection projects are on the new connection: https://review.rdoproject.org/zuul/projects

**Comment by TristanCacqueray** [comment]
According to https://opendev.org/zuul/zuul/src/branch/master/zuul/executor/common.py#L183 , it seems like the connection is defined by the full name, which match the first application.

**Comment by pabelanger** [comment]
@TristanCacqueray let me revert my change to zuul.a.c, and see if I am seeing the same issue. While I tested with noop jobs, I thought I had a tox jobs working too.

Either way, if not working, seems like a zuul bug.

**Comment by TristanCacqueray** [comment]
Well if this is a bug, then we should probably disable the new connection to prevent it from being assign to the wrong project.

**Comment by pabelanger** [comment]
yes, good idea. Lets disable for now, in the morning I'll reconfirm on zuul.a.c, using my personal repo and our token.

**Comment by pabelanger** [comment]
2021-07-13 23:53:30,792 ERROR zuul.AnsibleJob: [e: 2e16fc30-e435-11eb-9c8c-299fdfc81e0c] [build: 1c93a959839a4a098d4a3c130e2a9d42] Exception while executing job
Traceback (most recent call last):
  File "/opt/venv/zuul-4.6.0/lib/python3.6/site-packages/zuul/executor/server.py", line 1026, in execute
    self._execute()
  File "/opt/venv/zuul-4.6.0/lib/python3.6/site-packages/zuul/executor/server.py", line 1144, in _execute
    repo_state[task.connection_name][task.project_name]
KeyError: 'pabelanger/pabelanger-sandbox1'

Can confirm, so it does look like  bug in zuul. For the AnsibleJob class.

**Comment by TristanCacqueray** [comment]
Could you please re-open and recheck, the Zuul bug should now be fixed.

**Comment by TristanCacqueray** [comment]
@sshnaidm is `build-test-packages : Build collection` output in the build artifacts? If not, you could change the redirection to `~/zuul-output/logs/collection-build.log`

**Comment by sshnaidm** [comment]
Ok, let's try again

**Comment by sshnaidm** [comment]
@pabelanger @TristanCacqueray seems like everything works!

**Pull request closed without merging**
