### PR TITLE
DNM

### PR DESCRIPTION
**Pull request by rohitthakur2590**
##### SUMMARY

Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1651

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by rohitthakur2590** [comment]
recheck

**Comment by rohitthakur2590** [comment]
recheck

**Comment by Qalthos** [comment]
@justjais I proposed https://github.com/ansible/ansible-zuul-jobs/pull/1622 before your 1624, can we reconcile the two of those?

**Comment by rohitthakur2590** [comment]
recheck

**Pull request closed without merging**
