### PR TITLE
Adding exception handling for network template deepformat call

### PR DESCRIPTION
**Pull request by justjais**
##### SUMMARY

Adding exception handling for network template `deepformat` call, which might result in failure where parsing regex is common for global n child config and we need to segregate based on child config on certain shared parameter available to child regex match.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

network_template

##### ADDITIONAL INFORMATION

```paste below
router bgp 65000
 neighbor 192.0.2.1 remote-as 100
 neighbor 192.0.2.1 description replace neighbor
 !
 address-family ipv4 multicast vrf blue
    neighbor 192.0.2.1 remote-as 100
 exit-address-family
```
Now, for AF config if we segregate based on AFI shared val since `remote-as` regex is common for parent n child config, `deepformat` w/o the exception handling would result in traceback which isn’t expected, and with exception handling, in place, it'd continue the search in the entire config and then child config `remote-as` would get matched based on AFI formatting

### CODE REVIEW

**Comment by NilashishC** [comment]
A little modification in the parser would make this work. I ran the sample config lines you shared against the following parsers.
```
{
            "name": "as_number",
            "getval": re.compile(
                r"""
                ^router\sbgp\s(?P<as_number>\S+)
                $""", re.VERBOSE
            ),
            "setval": "router bgp {{ as_number }}",
            "result": {
                "as_number": "{{ as_number }}",
            },
            "shared": True
        },
        {
            "name": "address_family",
            "getval": re.compile(
                r"""
                \s+address-family
                \s(?P<afi>\S+) 
                \s(?P<safi>\S+)
                \svrf\s(?P<vrf>\S+)
                $""",
                re.VERBOSE,
            ),
            "setval": "address-family {{ afi }}{{ (' ' + safi) if safi is defined }}",
            "result": {
                "address_family": {
                    '{{ afi + "_" + safi|d() + "_" + vrf|d() }}': {
                        "vrf": "{{ vrf }}",
                        "afi": "{{ afi }}",
                        "safi": "{{ safi }}",
                    }
                }
            },
            "shared": True,
        },
        {
            "name": "neighbor",
            "getval": re.compile(
                r"""
                \s+neighbor\s(?P<nbr_addr>\S+)
                \sremote-as\s(?P<remote_as>\S+)
                $""",
                re.VERBOSE,
            ),
            "setval": "",
            "result": {
                "address_family": {
                    '{{ afi|d() + "_" + safi|d() + "_" + vrf|d() }}': {
                        "neighbors": {
                            "{{ nbr_addr }}": {
                                "neighbor_address": "{{ nbr_addr }}",
                                "remote_as": "{{ remote_as }}",
                            }
                        }
                    }
                }
            }
}
```

The data returned by the engine (before conversion in the resource facts class) is:
```
{
    "address_family": {
        "__": {
            "neighbors": {
                "192.0.2.1": {
                    "neighbor_address": "192.0.2.1",
                    "remote_as": 100,
                }
            }
        },
        "ipv4_multicast_blue": {
            "afi": "ipv4",
            "neighbors": {
                "192.0.2.1": {
                    "neighbor_address": "192.0.2.1",
                    "remote_as": 100,
                }
            },
            "safi": "multicast",
            "vrf": "blue",
        },
    },
    "as_number": 65000,
}
```
The first entry with `__` is essentially the global entries which we want to discard for this module.

Adding an try-catch block to mask an Exception for cases like this is not desirable and may lead to unintended errors like the engine not failing where it should.

**Review by NilashishC — CHANGES_REQUESTED** [review]
A little modification in the parser would make this work. I ran the sample config lines you shared against the following parsers.
```
{
            "name": "as_number",
            "getval": re.compile(
                r"""
                ^router\sbgp\s(?P<as_number>\S+)
                $""", re.VERBOSE
            ),
            "setval": "router bgp {{ as_number }}",
            "result": {
                "as_number": "{{ as_number }}",
            },
            "shared": True
        },
        {
            "name": "address_family",
            "getval": re.compile(
                r"""
                \s+address-family
                \s(?P<afi>\S+) 
                \s(?P<safi>\S+)
                \svrf\s(?P<vrf>\S+)
                $""",
                re.VERBOSE,
            ),
            "setval": "address-family {{ afi }}{{ (' ' + safi) if safi is defined }}",
            "result": {
                "address_family": {
                    '{{ afi + "_" + safi|d() + "_" + vrf|d() }}': {
                        "vrf": "{{ vrf }}",
                        "afi": "{{ afi }}",
                        "safi": "{{ safi }}",
                    }
                }
            },
            "shared": True,
        },
        {
            "name": "neighbor",
            "getval": re.compile(
                r"""
                \s+neighbor\s(?P<nbr_addr>\S+)
                \sremote-as\s(?P<remote_as>\S+)
                $""",
                re.VERBOSE,
            ),
            "setval": "",
            "result": {
                "address_family": {
                    '{{ afi|d() + "_" + safi|d() + "_" + vrf|d() }}': {
                        "neighbors": {
                            "{{ nbr_addr }}": {
                                "neighbor_address": "{{ nbr_addr }}",
                                "remote_as": "{{ remote_as }}",
                            }
                        }
                    }
                }
            }
}
```

The data returned by the engine (before conversion in the resource facts class) is:
```
{
    "address_family": {
        "__": {
            "neighbors": {
                "192.0.2.1": {
                    "neighbor_address": "192.0.2.1",
                    "remote_as": 100,
                }
            }
        },
        "ipv4_multicast_blue": {
            "afi": "ipv4",
            "neighbors": {
                "192.0.2.1": {
                    "neighbor_address": "192.0.2.1",
                    "remote_as": 100,
                }
            },
            "safi": "multicast",
            "vrf": "blue",
        },
    },
    "as_number": 65000,
}
```
The first entry with `__` is essentially the global entries which we want to discard for this module.

Adding an try-catch block to mask an Exception for cases like this is not desirable and may lead to unintended errors like the engine not failing where it should.

**Comment by justjais** [comment]
@NilashishC agreed on the suggestion and had already tried that but the PR fix seemed more reasonable to me hence the change but also I agree on the point of unintended error being missed in that case IMO we should fail the execution gracefully with exception msg instead of showing the traceback.

**Comment by NilashishC** [comment]
In no case should we continue to execute if there's an UndefinedError while parsing. If the try-catch block is removed, the UndefinedError is automatically propagated and execution is halted, I believe. I don't see why we need to re-raise the exception again.

**Comment by justjais** [comment]
@NilashishC I was suggesting something like:

**Pull request closed without merging**
