### PR TITLE
Remove tests/sanity/requirements.txt

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
Depends-on: https://github.com/ansible-collections/vyos.vyos/pull/129

https://github.com/ansible-collections/overview/issues/43

### CODE REVIEW

**Comment by Andersson007** [comment]
recheck

**Comment by Andersson007** [comment]
recheck

**Comment by Andersson007** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Comment by Andersson007** [comment]
@Qalthos thanks for helping!

**Pull request merged**
