### PR TITLE
Remove redirects for 2023-02 release

### PR DESCRIPTION
**Pull request by Qalthos**
##### SUMMARY

Depends-on: https://github.com/ansible-collections/arista.eos/pull/394
Depends-on: https://github.com/ansible-collections/cisco.ios/pull/711
Depends-on: https://github.com/ansible-collections/cisco.iosxr/pull/307
Depends-on: https://github.com/ansible-collections/cisco.nxos/pull/602
Depends-on: https://github.com/ansible-collections/vyos.vyos/pull/286

##### ISSUE TYPE

- Removal Pull Request

### CODE REVIEW

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Review by KB-perByte — APPROVED** [review]

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Pull request merged**
