### PR TITLE
Attempt to clarify the return situation for cli_config

### PR DESCRIPTION
**Pull request by Qalthos**
Expose diff if we have it.

##### ISSUE TYPE

- Docs Pull Request
- Feature Pull Request

##### COMPONENT NAME

cli_config

### CODE REVIEW

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Review by samccann — APPROVED** [review]
docs portion LGTM

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Pull request merged**
