### PR TITLE
Update bindep to Python 3.9

### PR DESCRIPTION
**Pull request by Qalthos**
Depends-on: https://github.com/ansible-collections/ansible.netcommon/pull/390

##### SUMMARY

Shift dependencies to python 3.9 packages and add rhel-9 lines for future use

### CODE REVIEW

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Comment by trishnaguha** [comment]
@Qalthos Can we get this PR merged?

**Comment by Qalthos** [comment]
recheck

**Pull request merged**
