### PR TITLE
Gracefully handle connection closing in pylibssh

### PR DESCRIPTION
**Pull request by Qalthos**
##### SUMMARY

This roughly mirrors the handling of a closed socket in paramiko, only paramiko does not raise an exception to catch.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

network_cli

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by Qalthos** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Review by ganeshrn — APPROVED** [review]

**Review by NilashishC — APPROVED** [review]

**Comment by Qalthos** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Review by ganeshrn — APPROVED** [review]
lgtm
Thank you!

**Pull request merged**
