### PR TITLE
Deprecate napalm connection plugin

### PR DESCRIPTION
**Pull request by Qalthos**
Depends-On: https://github.com/ansible-collections/ansible.netcommon/pull/54

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

napalm

### CODE REVIEW

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Pull request merged**
