### PR TITLE
Remove ipaddress from netcommon

### PR DESCRIPTION
**Pull request by Qalthos**
##### SUMMARY

Depends-on: https://github.com/ansible-collections/vyos.vyos/pull/120

##### ISSUE TYPE

- Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by felixfontein** [comment]
We already vendored it in community.crypto and community.general to avoid a collection dependency on ansible.netcommon just for that one file.

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Pull request merged**
