### PR TITLE
Add retries argument to httpapi.send

### PR DESCRIPTION
**Pull request by Qalthos**
##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

httpapi

### CODE REVIEW

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Review by NilashishC — APPROVED** [review]

**Comment by Qalthos** [comment]
recheck

**Pull request merged**
