### PR TITLE
Add missing license headers to module_utils code

### PR DESCRIPTION
**Pull request by Qalthos**
##### SUMMARY

I need positive confirmation from @justjais @NilashishC @pabelanger and @rohitthakur2590 that the license is acceptable.

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

network_template
resource_module

### CODE REVIEW

**Review by pabelanger — APPROVED** [review]
+1

**Comment by NilashishC** [comment]
This would need updates since #180 is now merged. But I'm +1 with the license added.

**Comment by Qalthos** [comment]
I also need an approval from @GomathiselviS for the rm_base files

**Comment by Qalthos** [comment]
recheck

**Review by justjais — APPROVED** [review]

**Review by GomathiselviS — APPROVED** [review]

**Review by rohitthakur2590 — APPROVED** [review]

**Review by NilashishC — APPROVED** [review]

**Pull request merged**
