### PR TITLE
Add documentation for ansible-pylibssh requirement

### LINKED ISSUE #240: ansible-pylibssh should be mentioned in the ssh_type parameter
https://github.com/ansible-collections/ansible.netcommon/blob/main/docs/ansible.netcommon.network_cli_connection.rst

### PR DESCRIPTION
**Pull request by Qalthos**
Depends-on: https://github.com/ansible-collections/arista.eos/pull/183
Depends-on: https://github.com/ansible-collections/cisco.ios/pull/284
Depends-on: https://github.com/ansible-collections/junipernetworks.junos/pull/161
Depends-on: https://github.com/ansible-collections/vyos.vyos/pull/140

##### SUMMARY

Fixes #240

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

network_cli

### CODE REVIEW

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Review by samccann — APPROVED** [review]

**Comment by Qalthos** [comment]
recheck

**Pull request merged**
