### PR TITLE
netconf_doc updates, other doc changes due to codeblock change in col…

### PR DESCRIPTION
**Pull request by cidrblock**
##### SUMMARY
Add detailed example in netconf get and config using native and xmltodict
Other doc codeblock updated to yaml

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
netconf_get
netconf_config

### CODE REVIEW

**Review by Qalthos — APPROVED** [review]

**Review by ganeshrn — APPROVED** [review]

**Comment by ganeshrn** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Comment by cidrblock** [comment]
recheck

**Pull request merged**
