### PR TITLE
Toggle import_modules on

### PR DESCRIPTION
**Pull request by Qalthos**
##### SUMMARY

Depends-On: https://github.com/ansible-collections/arista.eos/pull/346

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

httpapi
netconf
network_cli

### CODE REVIEW

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Comment by Qalthos** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Pull request merged**
